[window]
opacity = 1

[font]
# Cambia el 12.0 por el tamaño que prefieras (ej. 14.0 o 16.0)
size = 6.0

[font.normal]
# Asegúrate de poner el nombre exacto de tu fuente
family = "Hack"
style = "Regular"

[font.bold]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Italic"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"